name: Build Rancher Server

on:
  workflow_dispatch:
    inputs:
      PackageVersion:
# 测试通过v2.5.9-v2.5.11,v2.4.16-v2.4.17
        description: 'Select Build Rancher version'     
        required: true
        default: 'v2.4.17'
      Skipcheck_Result:
        description: 'Select skip validate and test(true|false)'     
        required: true
        default: 'true'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
        
 #   - name: Dump GitHub context
 #     env:
 #       packageName: v2.5.9
      #run: echo "::set-env name=packageName::v1.18.2"
      #run: echo '${{ env.packageName }}'
 #     run: echo "packageName=${{ env.packageName }}" >> $GITHUB_ENV

    - name: Get Input Rancher Version And Select skip ci Result
      run: |
       echo '${{ github.event.inputs.PackageVersion }}'
       echo "${{ github.event.inputs.Skipcheck_Result }}"
       
        

    - name: Get workpath
      run: |
       pwd
       who -b
       hostname


    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/v2.5+\.[0-20]+$ ]]; then
            echo ::set-output name=match::true
          fi
          
    - name: Build
      if: steps.check-tag.outputs.match == 'true'
      run: |
        echo "Tag is a match"


      

