name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
         python-version: 3.7
        
      # Runs a single command using the runners shell
      - name: install pkg and pip module
        run: |
         sudo wget http://www.linuxidc.com/files/repo/google-chrome.list -P /etc/apt/sources.list.d/
         wget -q -O - https://dl.google.com/linux/linux_signing_key.pub  | sudo apt-key add -
         sudo apt-get update
         sudo apt-get install google-chrome-stable
         wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
         unzip chromedriver_linux64.zip && sudo mv chromedriver /usr/sbin/
         pip3 install selenium
         pip install pyperclip

      # Runs a set of commands using the runners shell
      - name: Run python script
        run: |
          python3.7 click-ssr.py
