name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
         python-version: 3.7
        
      # Runs a single command using the runners shell
      - name: install pkg and pip module
        run: |
         wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
         sudo apt install ./google-chrome-stable_current_amd64.deb
         wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
         unzip chromedriver_linux64.zip && sudo mv chromedriver /usr/sbin/
         pip3 install selenium
         pip install pyperclip

      # Runs a set of commands using the runners shell
      - name: Run python script
        run: |
          python3.7 click-ssr.py
